apiVersion: v1
kind: Secret
metadata:
        name: ceph-secret
data:
        key: < here key : get it on ceph monitor with : grep key /etc/ceph/ceph.client.kube.keyring |awk '{printf "%s", $NF}'|base64 > 

